# Generated by Django 5.2.17 on 2026-08-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_alter_product_barcode_and_more'),
        ('inventory', '0001_initial'),
        ('stores', '0002_alter_cashregister_options_alter_store_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'ordering': ('-created_at',), 'verbose_name': 'mouvement de stock', 'verbose_name_plural': 'mouvements de stock'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('store_id', 'product_id'), 'verbose_name': 'stock', 'verbose_name_plural': 'stocks'},
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('STOCK_IN', 'Entrée de stock'), ('SALE', 'Vente'), ('ADJUSTMENT', 'Ajustement')], max_length=16, verbose_name='type de mouvement'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='catalog.product', verbose_name='produit'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='quantity',
            field=models.IntegerField(verbose_name='quantité'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='reference',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='référence'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='stores.store', verbose_name='magasin'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='catalog.product', verbose_name='produit'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantité'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='stores.store', verbose_name='magasin'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
    ]
