# Generated by Django 5.2.17 on 2026-08-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorymovement_options_alter_stock_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stock',
            name='inventory_stock_quantity_nonnegative',
        ),
    ]
