# Generated by Django 5.2.17 on 2026-08-23 21:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_stock_inventory_stock_quantity_nonnegative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('STOCK_IN', 'Entrée de stock'), ('SALE', 'Vente'), ('ADJUSTMENT', 'Ajustement'), ('RETURN_IN', 'Retour remis en stock')], max_length=16, verbose_name='type de mouvement'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantité'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='quantité'),
        ),
    ]
