# Generated by Django 5.2.17 on 2026-09-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventorymovement_movement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('STOCK_IN', 'Entrée de stock'), ('SALE', 'Vente'), ('ADJUSTMENT', 'Ajustement'), ('RETURN_IN', 'Retour remis en stock'), ('CANCELLATION', 'Vente annulée')], max_length=16, verbose_name='type de mouvement'),
        ),
    ]
