# Generated by Django 5.2.17 on 2026-09-30 12:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_low_stock_threshold'),
        ('inventory', '0005_alter_inventorymovement_movement_type'),
        ('stores', '0003_storeassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCostChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('INITIAL', 'Initialisation'), ('CORRECTION', 'Correction'), ('IMPORT', 'Import')], max_length=16, verbose_name='origine')),
                ('previous_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='ancien coût')),
                ('new_cost', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='nouveau coût')),
                ('quantity_at_change', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='stock au moment du changement')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='motif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='le')),
            ],
            options={
                'verbose_name': 'changement de coût',
                'verbose_name_plural': 'changements de coût',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to=settings.AUTH_USER_MODEL, verbose_name='créé par'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Coût d'une unité appliqué à ce mouvement : prix d'achat pour une entrée, coût moyen du moment pour une sortie. Vide si inconnu.", max_digits=14, null=True, verbose_name='coût unitaire'),
        ),
        migrations.AddField(
            model_name='stock',
            name='average_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Coût d'achat moyen pondéré d'une unité dans ce magasin. Vide quand il n'est pas connu — jamais 0 par défaut, ce qui gonflerait la marge. Ne se modifie que par une réception ou une initialisation tracée, jamais à la main.", max_digits=14, null=True, verbose_name='coût moyen'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__isnull', True), ('unit_cost__gte', Decimal('0')), _connector='OR'), name='inventory_movement_unit_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('average_unit_cost__isnull', True), ('average_unit_cost__gte', Decimal('0')), _connector='OR'), name='inventory_stock_average_cost_nonnegative'),
        ),
        migrations.AddField(
            model_name='stockcostchange',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Vide pour un changement fait par le système (migration, import).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_cost_changes', to=settings.AUTH_USER_MODEL, verbose_name='modifié par'),
        ),
        migrations.AddField(
            model_name='stockcostchange',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_cost_changes', to='catalog.product', verbose_name='produit'),
        ),
        migrations.AddField(
            model_name='stockcostchange',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_cost_changes', to='stores.store', verbose_name='magasin'),
        ),
        migrations.AddIndex(
            model_name='stockcostchange',
            index=models.Index(fields=['store', 'product', 'created_at'], name='inventory_cost_change_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockcostchange',
            constraint=models.CheckConstraint(condition=models.Q(('new_cost__gte', Decimal('0'))), name='inventory_cost_change_new_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockcostchange',
            constraint=models.CheckConstraint(condition=models.Q(('previous_cost__isnull', True), ('previous_cost__gte', Decimal('0')), _connector='OR'), name='inventory_cost_change_previous_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockcostchange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source', 'INITIAL'), _negated=True), ('previous_cost__isnull', True), _connector='OR'), name='inventory_cost_change_initial_from_unknown'),
        ),
        migrations.AddConstraint(
            model_name='stockcostchange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source', 'CORRECTION'), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='inventory_cost_change_correction_has_reason'),
        ),
    ]
