# Generated by Django 5.2.17 on 2026-09-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_initialize_average_cost_from_purchase_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockValuation',
            fields=[
            ],
            options={
                'verbose_name': 'valorisation du stock',
                'verbose_name_plural': 'valorisation du stock',
                'permissions': (('set_cost_stockvaluation', "Peut définir le coût d'un stock"),),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.stock',),
        ),
    ]
