# Generated by Django 5.2.17 on 2026-09-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stock_valuation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='average_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Coût d'achat moyen d'une unité dans ce magasin, recalculé à chaque réception. Vide tant qu'il n'est pas connu.", max_digits=14, null=True, verbose_name='coût moyen'),
        ),
    ]
