# Generated by Django 5.2.17 on 2026-09-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_manager_help_texts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('store_id', 'product_id'), 'verbose_name': 'stock', 'verbose_name_plural': 'état du stock'},
        ),
    ]
