# Generated by Django 5.2.17 on 2026-10-01 10:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('slug', models.SlugField(help_text='Court et stable, sert de préfixe aux identifiants (ex. « ndiaye »).', max_length=64, unique=True, verbose_name='identifiant')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspendue')], default='ACTIVE', max_length=16, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='tenancy_organization_name_not_empty'), models.CheckConstraint(condition=models.Q(('status__in', ('ACTIVE', 'SUSPENDED'))), name='tenancy_organization_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Propriétaire'), ('MANAGER', 'Gérant'), ('CASHIER', 'Caissier')], max_length=16, verbose_name='rôle')),
                ('can_view_costs', models.BooleanField(default=False, help_text="Pour un gérant : coût d'achat, valorisation du stock et marges. Un propriétaire les voit toujours, un caissier jamais.", verbose_name='voit les coûts et marges')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='tenancy.organization', verbose_name='organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'membre',
                'verbose_name_plural': 'membres',
                'ordering': ('organization__name', 'user__username'),
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='tenancy_unique_membership_per_organization'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='tenancy_one_active_membership_per_user'), models.CheckConstraint(condition=models.Q(('role__in', ('OWNER', 'MANAGER', 'CASHIER'))), name='tenancy_membership_role_valid')],
            },
        ),
    ]
