# Generated by Django 5.2.17 on 2026-10-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0003_manager_store_assignments"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmembership",
            name="approval_pin",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="code PIN de validation"
            ),
        ),
    ]
