# Generated by Django 5.2.17 on 2026-09-29 20:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0002_alter_cashsession_options_and_more'),
        ('stores', '0003_storeassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='nom')),
                ('requires_description', models.BooleanField(default=False, help_text='La catégorie seule ne dit pas ce qui a été payé (ex. « Autre »).', verbose_name='description obligatoire')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre d’affichage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
            ],
            options={
                'verbose_name': 'catégorie de dépense',
                'verbose_name_plural': 'catégories de dépenses',
                'ordering': ('sort_order', 'name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='expenses_category_name_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=16, unique=True, verbose_name='référence')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money')], max_length=16, verbose_name='mode de paiement')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('document_reference', models.CharField(blank=True, default='', help_text='Numéro de facture ou de transaction, ex. « SENELEC-… ».', max_length=64, verbose_name='référence du justificatif')),
                ('status', models.CharField(choices=[('POSTED', 'Enregistrée'), ('CANCELLED', 'Annulée')], default='POSTED', max_length=16, verbose_name='statut')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('idempotency_key', models.UUIDField(unique=True, verbose_name='clé d’idempotence')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='saisie le')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='annulée le')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name='motif d’annulation')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='annulée par')),
                ('cash_session', models.ForeignKey(blank=True, help_text="Obligatoire pour une dépense en espèces : l'argent sort d'un tiroir.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='cash.cashsession', verbose_name='session de caisse')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='saisie par')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='stores.store', verbose_name='magasin')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'dépense',
                'verbose_name_plural': 'dépenses',
                'ordering': ('-occurred_at', '-created_at'),
                'permissions': (('cancel_expense', 'Peut annuler une dépense'),),
                'indexes': [models.Index(fields=['cash_session', 'payment_method', 'status'], name='expenses_session_idx'), models.Index(fields=['store', 'occurred_at'], name='expenses_store_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='expenses_amount_positive'), models.CheckConstraint(condition=models.Q(('payment_method__in', ('CASH', 'WAVE', 'ORANGE_MONEY'))), name='expenses_payment_method_valid'), models.CheckConstraint(condition=models.Q(('status__in', ('POSTED', 'CANCELLED'))), name='expenses_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('payment_method', 'CASH'), _negated=True), ('cash_session__isnull', False), _connector='OR'), name='expenses_cash_requires_session'), models.CheckConstraint(condition=models.Q(models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('status', 'POSTED')), models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('status', 'CANCELLED'), models.Q(('cancellation_reason', ''), _negated=True)), _connector='OR'), name='expenses_cancellation_consistent')],
            },
        ),
    ]
