# Generated by Django 5.2.17 on 2026-09-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_default_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-occurred_at', '-created_at'), 'permissions': (('cancel_expense', 'Peut annuler une dépense'),), 'verbose_name': 'dépense', 'verbose_name_plural': 'dépenses saisies'},
        ),
    ]
