# Generated by Django 5.2.17 on 2026-10-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expensecategory_organization'),
        ('tenancy', '0003_manager_store_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=64, verbose_name='nom'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='expenses_unique_category_name_per_organization'),
        ),
    ]
