# Generated by Django 5.2.17 on 2026-08-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedSyncEvent',
            fields=[
                ('event_id', models.UUIDField(primary_key=True, serialize=False, verbose_name="identifiant d'événement")),
                ('terminal_id', models.UUIDField(verbose_name='identifiant de terminal')),
                ('event_type', models.CharField(choices=[('SALE_COMPLETED', 'Vente terminée')], max_length=32, verbose_name="type d'événement")),
                ('entity_id', models.UUIDField(verbose_name="identifiant de l'entité (ex. sale_id)")),
                ('stock_discrepancy', models.BooleanField(default=False, help_text='Vrai si cette vente a fait passer un stock sous zéro.', verbose_name='divergence de stock')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='traité le')),
            ],
            options={
                'verbose_name': 'événement de synchronisation traité',
                'verbose_name_plural': 'événements de synchronisation traités',
                'ordering': ('-processed_at',),
                'indexes': [models.Index(fields=['entity_id'], name='sync_event_entity_id_idx'), models.Index(fields=['terminal_id'], name='sync_event_terminal_id_idx')],
            },
        ),
    ]
