# Generated by Django 5.2.17 on 2026-09-29 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processedsyncevent',
            name='pushed_by',
            field=models.ForeignKey(blank=True, help_text="Utilisateur connecté sur la caisse quand l'événement a été envoyé. Peut différer du caissier de la vente : sur une caisse partagée, un collègue transmet les ventes restées en attente.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pushed_sync_events', to=settings.AUTH_USER_MODEL, verbose_name='transmis par'),
        ),
    ]
