# Generated by Django 5.2.17 on 2026-10-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0003_processedsyncevent_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="processedsyncevent",
            name="catalog_price_discrepancy",
            field=models.BooleanField(
                default=False,
                help_text="Vrai si le prix catalogue envoyé par le poste diffère du prix catalogue du serveur pour au moins un article (changement de prix pendant la coupure, ou poste altéré).",
                verbose_name="prix catalogue à vérifier",
            ),
        ),
    ]
