# Generated by Django 5.2.17 on 2026-10-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0004_offline_catalog_price_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="processedsyncevent",
            name="unapproved_discount",
            field=models.BooleanField(
                default=False,
                help_text="Vrai si la vente porte une remise au-delà de ce qu'un caissier accorde seul, sans validation de gérant valable.",
                verbose_name="remise non validée",
            ),
        ),
    ]
