# Generated by Django 5.2.17 on 2026-08-17

import decimal
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("barcode", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "selling_price",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("selling_price__gte", decimal.Decimal("0"))
                        ),
                        name="catalog_product_selling_price_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("purchase_price__isnull", True),
                            ("purchase_price__gte", decimal.Decimal("0")),
                            _connector="OR",
                        ),
                        name="catalog_product_purchase_price_nonnegative",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("barcode__isnull", False)),
                        fields=("barcode",),
                        name="catalog_unique_product_barcode_when_set",
                    ),
                ],
            },
        )
    ]
