# Generated by Django 5.2.17 on 2026-08-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_unit',
            field=models.CharField(choices=[('UNIT', 'Unité'), ('KG', 'Kilogramme')], default='UNIT', max_length=8, verbose_name='unité de vente'),
        ),
    ]
