# Generated by Django 5.2.17 on 2026-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_format_existing_product_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Laisser vide pour utiliser le seuil par défaut du commerce (LOW_STOCK_THRESHOLD_DEFAULT).', null=True, verbose_name='seuil de stock faible'),
        ),
    ]
