# Generated by Django 5.2.17 on 2026-09-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_low_stock_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix payé au fournisseur lors de la dernière réception, mis à jour à chaque réception et proposé pour la suivante. Le modifier ne change pas la valeur du stock, calculée au coût moyen par magasin.', max_digits=14, null=True, verbose_name="dernier prix d'achat"),
        ),
    ]
