# Generated by Django 5.2.17 on 2026-09-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='En dessous de cette quantité, le produit est signalé en stock faible. Laisser vide pour utiliser le seuil par défaut de la boutique.', null=True, verbose_name='seuil de stock faible'),
        ),
    ]
