# Generated by Django 5.2.17 on 2026-10-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_organization'),
        ('tenancy', '0003_manager_store_assignments'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='catalog_unique_product_barcode_when_set',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('organization', 'barcode'), name='catalog_unique_product_barcode_per_organization'),
        ),
    ]
