# Generated by Django 5.2.17 on 2026-09-28 13:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0005_alter_payment_sale'),
        ('stores', '0003_storeassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('phone', models.CharField(blank=True, help_text='Format normalisé E.164 (+221771234567). Obligatoire à la création depuis la caisse ; facultatif pour un import ou une saisie admin.', max_length=16, null=True, verbose_name='téléphone')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='stores.store', verbose_name='magasin')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CustomerLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('CREDIT_SALE', 'Achat à crédit'), ('PAYMENT', 'Paiement'), ('RETURN_CREDIT', 'Retour déduit du cahier'), ('ADJUSTMENT', 'Ajustement'), ('OPENING_BALANCE', 'Solde d’ouverture'), ('REVERSAL', 'Annulation d’écriture')], max_length=16, verbose_name='type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant')),
                ('reference', models.CharField(blank=True, default='', help_text='Référence externe libre, ex. « ACCESS:1234 » pour une reprise.', max_length=64, verbose_name='référence')),
                ('reason', models.TextField(blank=True, default='', verbose_name='motif')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='customers.customer', verbose_name='client')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='customers.customerledgerentry', verbose_name='annule l’écriture')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_ledger_entries', to='sales.sale', verbose_name='vente')),
                ('sale_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_ledger_entries', to='sales.salereturn', verbose_name='retour')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_ledger_entries', to='stores.store', verbose_name='magasin')),
            ],
            options={
                'verbose_name': 'écriture du cahier',
                'verbose_name_plural': 'écritures du cahier',
                'ordering': ('-occurred_at', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['store', 'name'], name='customers_store_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False)), fields=('store', 'phone'), name='customers_unique_phone_per_store', violation_error_message='Un client existe déjà avec ce numéro dans ce magasin.'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='customers_customer_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('phone__isnull', True), ('phone__startswith', '+'), _connector='OR'), name='customers_customer_phone_normalized'),
        ),
        migrations.AddIndex(
            model_name='customerledgerentry',
            index=models.Index(fields=['customer', 'occurred_at'], name='customers_entry_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledgerentry',
            index=models.Index(fields=['store', 'occurred_at'], name='customers_entry_store_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount', Decimal('0')), _negated=True), name='customers_entry_amount_nonzero', violation_error_message='Le montant ne peut pas être nul.'),
        ),
        migrations.AddConstraint(
            model_name='customerledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('entry_type', 'CREDIT_SALE'), ('reversal_of__isnull', True), ('sale__isnull', False), ('sale_return__isnull', True)), models.Q(('amount__lt', 0), ('entry_type', 'PAYMENT'), ('reversal_of__isnull', True), ('sale__isnull', True), ('sale_return__isnull', True)), models.Q(('amount__lt', 0), ('entry_type', 'RETURN_CREDIT'), ('reversal_of__isnull', True), ('sale__isnull', False), ('sale_return__isnull', False)), models.Q(('entry_type', 'ADJUSTMENT'), ('reversal_of__isnull', True), ('sale__isnull', True), ('sale_return__isnull', True), models.Q(('reason', ''), _negated=True)), models.Q(('amount__gt', 0), ('entry_type', 'OPENING_BALANCE'), ('reversal_of__isnull', True), ('sale__isnull', True), ('sale_return__isnull', True)), models.Q(('entry_type', 'REVERSAL'), ('reversal_of__isnull', False), ('sale__isnull', True), ('sale_return__isnull', True), models.Q(('reason', ''), _negated=True)), _connector='OR'), name='customers_entry_type_rules'),
        ),
        migrations.AddConstraint(
            model_name='customerledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'CREDIT_SALE')), fields=('sale',), name='customers_one_credit_entry_per_sale'),
        ),
        migrations.AddConstraint(
            model_name='customerledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'RETURN_CREDIT')), fields=('sale_return',), name='customers_one_credit_entry_per_return'),
        ),
        migrations.AddConstraint(
            model_name='customerledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'OPENING_BALANCE')), fields=('customer',), name='customers_one_opening_balance_per_customer', violation_error_message='Ce client a déjà un solde d’ouverture.'),
        ),
    ]
