# Generated by Django 5.2.17 on 2026-09-28 14:11

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_alter_cashsession_options_and_more'),
        ('customers', '0001_initial'),
        ('sales', '0006_sale_customer_credit'),
        ('stores', '0003_storeassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=16, unique=True, verbose_name='référence')),
                ('method', models.CharField(choices=[('CASH', 'Espèces'), ('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money')], max_length=16, verbose_name='mode de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant')),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='montant reçu')),
                ('change_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='monnaie rendue')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='ancien solde')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='nouveau solde')),
                ('idempotency_key', models.UUIDField(unique=True, verbose_name='clé d’idempotence')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='encaissé le')),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to='cash.cashsession', verbose_name='session de caisse')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to=settings.AUTH_USER_MODEL, verbose_name='encaissé par')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer', verbose_name='client')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to='stores.store', verbose_name='magasin')),
            ],
            options={
                'verbose_name': 'paiement client',
                'verbose_name_plural': 'paiements clients',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='customerledgerentry',
            name='customer_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entry', to='customers.customerpayment', verbose_name='paiement client'),
        ),
        migrations.AddConstraint(
            model_name='customerledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer_payment__isnull', False), ('entry_type', 'PAYMENT')), models.Q(models.Q(('entry_type', 'PAYMENT'), _negated=True), ('customer_payment__isnull', True)), _connector='OR'), name='customers_entry_payment_link'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['cash_session', 'method'], name='customers_payment_session_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='customers_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='customerpayment',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after', django.db.models.expressions.CombinedExpression(models.F('balance_before'), '-', models.F('amount'))), ('balance_after__gte', Decimal('0'))), name='customers_payment_balance_snapshot_consistent'),
        ),
        migrations.AddConstraint(
            model_name='customerpayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('change_amount', django.db.models.expressions.CombinedExpression(models.F('received_amount'), '-', models.F('amount'))), ('change_amount__isnull', False), ('method', 'CASH'), ('received_amount__gte', models.F('amount')), ('received_amount__isnull', False)), models.Q(('change_amount__isnull', True), ('method__in', ('WAVE', 'ORANGE_MONEY')), ('received_amount__isnull', True)), _connector='OR'), name='customers_payment_details_match_method'),
        ),
    ]
