# Generated by Django 5.2.17 on 2026-09-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='Numéro international, ex. +221 77 123 45 67. Obligatoire pour un client créé depuis la caisse.', max_length=16, null=True, verbose_name='téléphone'),
        ),
    ]
