# Generated by Django 5.2.17 on 2026-08-17

import decimal
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Ouverte"), ("CLOSED", "Fermée")],
                        default="OPEN",
                        max_length=8,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                (
                    "closing_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "expected_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cash_register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_sessions",
                        to="stores.cashregister",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-opened_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "OPEN")),
                        fields=("cash_register",),
                        name="cash_unique_open_session_per_register",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ("OPEN", "CLOSED"))),
                        name="cash_session_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("opening_balance__gte", decimal.Decimal("0"))
                        ),
                        name="cash_session_opening_balance_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("closing_balance__isnull", True),
                            ("closing_balance__gte", decimal.Decimal("0")),
                            _connector="OR",
                        ),
                        name="cash_session_closing_balance_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expected_balance__isnull", True),
                            ("expected_balance__gte", decimal.Decimal("0")),
                            _connector="OR",
                        ),
                        name="cash_session_expected_balance_nonnegative",
                    ),
                ],
            },
        )
    ]
