# Generated by Django 5.2.17 on 2026-08-17 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
        ('stores', '0002_alter_cashregister_options_alter_store_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashsession',
            options={'ordering': ('-opened_at',), 'verbose_name': 'session de caisse', 'verbose_name_plural': 'sessions de caisse'},
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='cash_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='stores.cashregister', verbose_name='caisse'),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL, verbose_name='caissier'),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fermée le'),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='closing_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='solde de clôture'),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='écart'),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='expected_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='solde attendu'),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ouverte le'),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name="solde d'ouverture"),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ouverte'), ('CLOSED', 'Fermée')], default='OPEN', max_length=8, verbose_name='statut'),
        ),
    ]
