# Generated by Django 5.2.17 on 2026-08-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashregister',
            options={'ordering': ('store__name', 'name'), 'verbose_name': 'caisse', 'verbose_name_plural': 'caisses'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('name',), 'verbose_name': 'magasin', 'verbose_name_plural': 'magasins'},
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créée le'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to='stores.store', verbose_name='magasin'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifiée le'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
    ]
