# Generated by Django 5.2.17 on 2026-08-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stores", "0002_alter_cashregister_options_alter_store_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créée le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifiée le")),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_assignments", to="stores.store", verbose_name="magasin")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="store_assignments", to=settings.AUTH_USER_MODEL, verbose_name="utilisateur")),
            ],
            options={
                "verbose_name": "affectation à un magasin",
                "verbose_name_plural": "affectations aux magasins",
                "ordering": ("store__name", "user__username"),
                "constraints": [models.UniqueConstraint(fields=("user", "store"), name="stores_unique_user_assignment_per_store")],
            },
        ),
    ]
