# Generated by Django 5.2.17 on 2026-08-17

import decimal
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cash", "0001_initial"),
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("0"),
                        max_digits=14,
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "Terminée"),
                            ("CANCELLED", "Annulée"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cash_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="cash.cashsession",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ("COMPLETED", "CANCELLED"))),
                        name="sales_sale_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("subtotal__gte", decimal.Decimal("0"))
                        ),
                        name="sales_sale_subtotal_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("discount__gte", decimal.Decimal("0")))
                        & models.Q(("discount__lte", models.F("subtotal"))),
                        name="sales_sale_discount_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("total__gte", decimal.Decimal("0")))
                        & models.Q(
                            (
                                "total",
                                models.F("subtotal") - models.F("discount"),
                            )
                        ),
                        name="sales_sale_total_consistent",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("quantity", models.PositiveIntegerField()),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_items",
                        to="catalog.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="sales_item_quantity_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("unit_price__gte", decimal.Decimal("0"))
                        ),
                        name="sales_item_unit_price_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("line_total__gte", decimal.Decimal("0"))
                        )
                        & models.Q(
                            (
                                "line_total",
                                models.F("unit_price") * models.F("quantity"),
                            )
                        ),
                        name="sales_item_line_total_consistent",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Espèces"),
                            ("WAVE", "Wave"),
                            ("ORANGE_MONEY", "Orange Money"),
                        ],
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "received_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "change_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", decimal.Decimal("0"))),
                        name="sales_payment_amount_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("change_amount", models.F("received_amount") - models.F("amount")),
                            ("change_amount__isnull", False),
                            ("method", "CASH"),
                            ("received_amount__gte", models.F("amount")),
                            ("received_amount__isnull", False),
                        )
                        | models.Q(
                            ("change_amount__isnull", True),
                            ("method__in", ("WAVE", "ORANGE_MONEY")),
                            ("received_amount__isnull", True),
                        ),
                        name="sales_payment_details_match_method",
                    ),
                ],
            },
        ),
    ]
