# Generated by Django 5.2.17 on 2026-08-17 19:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_alter_cashsession_options_and_more'),
        ('catalog', '0002_alter_product_options_alter_product_barcode_and_more'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-created_at',), 'verbose_name': 'paiement', 'verbose_name_plural': 'paiements'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('-created_at',), 'verbose_name': 'vente', 'verbose_name_plural': 'ventes'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ('id',), 'verbose_name': 'article vendu', 'verbose_name_plural': 'articles vendus'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='change_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='monnaie rendue'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money')], max_length=16, verbose_name='mode de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='received_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='montant reçu'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='sales.sale', verbose_name='vente'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cash_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='cash.cashsession', verbose_name='session de caisse'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='caissier'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créée le'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='remise'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], max_length=10, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='sous-total'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='total de la ligne'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalog.product', verbose_name='produit'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='nom du produit'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='quantité'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sales.sale', verbose_name='vente'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='prix unitaire'),
        ),
    ]
