# Generated by Django 5.2.17 on 2026-08-17 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_payment_options_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Moment réel de la vente sur la caisse. Identique à created_at pour une vente en ligne ; peut être antérieur pour une vente synchronisée depuis le mode hors-ligne.', verbose_name='réalisée le'),
        ),
    ]
