# Generated by Django 5.2.17 on 2026-08-23 21:12

import django.db.models.deletion
import django.db.models.functions.math
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_catalog_unit_price(apps, schema_editor):
    SaleItem = apps.get_model("sales", "SaleItem")
    SaleItem.objects.filter(catalog_unit_price=0).update(
        catalog_unit_price=models.F("unit_price")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_alter_cashsession_options_and_more'),
        ('catalog', '0003_product_sale_unit'),
        ('sales', '0003_sale_occurred_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=16, unique=True, verbose_name='référence')),
                ('total_refund', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='total remboursé')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money')], max_length=16, verbose_name='mode de remboursement')),
                ('status', models.CharField(choices=[('COMPLETED', 'Terminé')], default='COMPLETED', max_length=10, verbose_name='statut')),
                ('idempotency_key', models.UUIDField(unique=True, verbose_name='clé d’idempotence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'retour',
                'verbose_name_plural': 'retours',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='prix remboursé')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant remboursé')),
                ('restock', models.BooleanField(default=True, verbose_name='remis en stock')),
            ],
            options={
                'verbose_name': 'article retourné',
                'verbose_name_plural': 'articles retournés',
                'ordering': ('id',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='saleitem',
            name='sales_item_unit_price_nonnegative',
        ),
        migrations.RemoveConstraint(
            model_name='saleitem',
            name='sales_item_line_total_consistent',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='catalog_unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='prix catalogue'),
        ),
        migrations.RunPython(backfill_catalog_unit_price, migrations.RunPython.noop),
        migrations.AddField(
            model_name='saleitem',
            name='sale_unit',
            field=models.CharField(choices=[('UNIT', 'Unité'), ('KG', 'Kilogramme')], default='UNIT', max_length=8, verbose_name='unité de vente'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantité'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', Decimal('0'))), name='sales_item_unit_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('catalog_unit_price__gte', Decimal('0'))), name='sales_item_catalog_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', Decimal('0')), ('line_total', django.db.models.functions.math.Round(models.F('unit_price') * models.F('quantity'), precision=2))), name='sales_item_line_total_consistent'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='cash_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_returns', to='cash.cashsession', verbose_name='session de caisse'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_returns', to=settings.AUTH_USER_MODEL, verbose_name='créé par'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='original_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale', verbose_name='vente originale'),
        ),
        migrations.AddField(
            model_name='salereturnitem',
            name='original_sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='sales.saleitem', verbose_name='article vendu'),
        ),
        migrations.AddField(
            model_name='salereturnitem',
            name='sale_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sales.salereturn', verbose_name='retour'),
        ),
        migrations.AddConstraint(
            model_name='salereturn',
            constraint=models.CheckConstraint(condition=models.Q(('total_refund__gt', 0)), name='sales_return_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='salereturnitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_return_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='salereturnitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='sales_return_item_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='salereturnitem',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__gt', 0)), name='sales_return_item_refund_positive'),
        ),
    ]
