# Generated by Django 5.2.17 on 2026-09-15 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salereturn_salereturnitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.sale', verbose_name='vente'),
        ),
    ]
