# Generated by Django 5.2.17 on 2026-09-28 13:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_alter_cashsession_options_and_more'),
        ('customers', '0001_initial'),
        ('sales', '0005_alter_payment_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Part du total non encaissée, inscrite au cahier du client. Ce n'est pas un paiement : sum(paiements) + mis au cahier = total.", max_digits=14, verbose_name='mis au cahier'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer', verbose_name='client'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('credit_amount__gte', Decimal('0')), ('credit_amount__lte', models.F('total'))), name='sales_sale_credit_amount_valid'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('credit_amount', Decimal('0')), ('customer__isnull', False), _connector='OR'), name='sales_sale_credit_requires_customer'),
        ),
    ]
