# Generated by Django 5.2.17 on 2026-09-28 15:32

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_alter_cashsession_options_and_more'),
        ('sales', '0006_sale_customer_credit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturn',
            name='credit_reduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Part du retour effacée de la dette du client, sur une vente mise au cahier. Jamais de l'argent : seul le reste est remboursé.", max_digits=14, verbose_name='déduit du cahier'),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Espèces'), ('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money')], help_text='Vide quand tout le retour a été déduit du cahier (aucun argent rendu).', max_length=16, null=True, verbose_name='mode de remboursement'),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='total_refund',
            field=models.DecimalField(decimal_places=2, help_text="Valeur des articles rendus. Elle réduit le chiffre d'affaires net ; l'argent réellement rendu en est la part hors cahier.", max_digits=14, verbose_name='valeur retournée'),
        ),
        migrations.AddConstraint(
            model_name='salereturn',
            constraint=models.CheckConstraint(condition=models.Q(('credit_reduction__gte', 0), ('credit_reduction__lte', models.F('total_refund'))), name='sales_return_credit_reduction_valid'),
        ),
        migrations.AddConstraint(
            model_name='salereturn',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit_reduction', models.F('total_refund')), ('payment_method__isnull', True)), models.Q(('payment_method__isnull', False), ('credit_reduction__lt', models.F('total_refund'))), _connector='OR'), name='sales_return_method_iff_money_refund'),
        ),
    ]
