# Generated by Django 5.2.17 on 2026-09-30 12:06

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_alter_cashsession_options_and_more'),
        ('catalog', '0005_product_low_stock_threshold'),
        ('customers', '0002_customer_payment'),
        ('sales', '0007_sale_return_credit_reduction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Coût moyen du produit dans le magasin au moment de la vente, figé : la marge d'une vente passée ne suit jamais le coût actuel. Vide si le coût n'était pas connu (ventes antérieures au suivi des coûts).", max_digits=14, null=True, verbose_name="coût d'achat unitaire"),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', 'occurred_at'], name='sales_sale_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='salereturn',
            index=models.Index(fields=['created_at'], name='sales_return_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__isnull', True), ('unit_cost__gte', Decimal('0')), _connector='OR'), name='sales_item_unit_cost_nonnegative'),
        ),
    ]
