# Generated by Django 5.2.17 on 2026-09-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_saleitem_unit_cost_and_report_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('-created_at',), 'permissions': (('view_profitability', 'Peut voir la rentabilité'),), 'verbose_name': 'vente', 'verbose_name_plural': 'ventes'},
        ),
    ]
