# Generated by Django 5.2.17 on 2026-09-30 14:56

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_view_profitability_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Part du total non encaissée, inscrite au cahier du client : ce qu'il reste à payer une fois les paiements déduits.", max_digits=14, verbose_name='mis au cahier'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Heure de la vente sur la caisse. Une vente faite sans connexion garde son heure réelle, même si elle arrive plus tard au serveur.', verbose_name='réalisée le'),
        ),
    ]
