# Generated by Django 5.2.17 on 2026-09-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_manager_help_texts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('-created_at',), 'permissions': (('view_profitability', 'Peut voir la rentabilité'),), 'verbose_name': 'ticket de vente', 'verbose_name_plural': 'tickets de vente'},
        ),
    ]
