# Generated by Django 5.2.17 on 2026-10-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0011_list_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="server_catalog_unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Vente hors ligne seulement : prix catalogue connu du serveur à la synchronisation, renseigné quand il diffère du prix catalogue envoyé par le poste.",
                max_digits=14,
                null=True,
                verbose_name="prix catalogue serveur",
            ),
        ),
    ]
