# Generated by Django 5.2.17 on 2026-10-02 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0012_offline_catalog_price_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="cancellation_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_sale_cancellations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="annulation validée par",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="cancellation_reason",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="motif d'annulation"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="annulée le"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cancelled_sales",
                to=settings.AUTH_USER_MODEL,
                verbose_name="annulée par",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="discount_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_sale_discounts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="remise validée par",
            ),
        ),
        migrations.AddField(
            model_name="salereturn",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_sale_returns",
                to=settings.AUTH_USER_MODEL,
                verbose_name="validé par",
            ),
        ),
    ]
